version: '3.7'
services: 
  backend:
    build:
      context: "./server-websocket"
      dockerfile: Dockerfile
    image: sergi0dev/repo:latest
    container_name: "server-websocket"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: timescaledb
    ports:
      - "8181:8181"
    networks:
      - app
  dbtimescale:
    image: timescale/timescaledb:2.1.1-pg13  
    container_name: "timescaledb"
    volumes:
      - my-app:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    networks:
      - app
volumes:
  my-app:
    name: my-volume
networks:
  app:
    name: app_docker
