name: Publish Docker image

on:
  push:
    branches:
     - dev
    paths:
     - server-websocket/**

defaults:
  run:
    working-directory: server-websocket

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.2
      - name: Push to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t app .
      - name: Tags
        run: |
          docker tag app ${{ secrets.DOCKER_USERNAME }}/repo:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/repo:latest

        # uses: mr-smithers-excellent/docker-build-push@v5
        # with:
        #   image: repo/tfg
        #   tags: latest
        #   registry: docker.io
        #   directory: server-websocket
        #   dockerfile: server-websocket/Dockerfile
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}