name: Publish Docker image

on:
  push:
    branches:
     - main
    paths:
     - server-websocket/**

defaults:
  run:
    working-directory: server-websocket

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.2
      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: NOMBRE_IMAGEN
          tags: latest
          registry: docker.io
          directory: DIRECTORIO
          dockerfile: DIRECTORIO/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
